/**
 * Conversation & Audio Export Utilities for Chatly Voice AI
 */

import { ChatMessage } from "../page";

export function exportConversationTranscript(messages: ChatMessage[], topicTitle = "Chatly Voice Conversation") {
  if (!messages || messages.length === 0) {
    alert("No conversation turns to export yet. Start speaking with Chatly first!");
    return;
  }

  const dateStr = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });
  const timeStr = new Date().toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });

  let content = `================================================================================\n`;
  content += `CHATLY VOICE AI - CONVERSATION TRANSCRIPT\n`;
  content += `Export Date: ${dateStr} at ${timeStr}\n`;
  content += `Total Turns: ${messages.length}\n`;
  content += `================================================================================\n\n`;

  messages.forEach((m, idx) => {
    const speakerLabel = m.sender === "user" ? "YOU (USER)" : `CHATLY AI [${m.model || "Voice Assistant"}]`;
    const timestamp = m.timestamp ? new Date(m.timestamp).toLocaleTimeString() : "";

    content += `[TURN #${idx + 1}] ${speakerLabel} (${timestamp})\n`;
    content += `--------------------------------------------------------------------------------\n`;
    content += `${m.text}\n\n`;

    if (m.toolUsed) {
      content += `⚡ Tool Executed: ${m.toolUsed.name} (${m.toolUsed.detail || JSON.stringify(m.toolUsed.args || {})})\n\n`;
    }
    if (m.ragSource) {
      content += `🧠 Knowledge Grounding: ${m.ragSource}\n\n`;
    }
    content += `\n`;
  });

  content += `================================================================================\n`;
  content += `End of Transcript - Generated by Chatly Voice AI Platform\n`;
  content += `================================================================================\n`;

  // Create download blob
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `chatly_transcript_${new Date().toISOString().slice(0, 10)}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportAudioFile(base64Audio: string, format = "audio/wav", filename = "chatly_voice.wav") {
  if (!base64Audio) {
    alert("No synthesized voice audio is available for this turn.");
    return;
  }

  try {
    const byteCharacters = atob(base64Audio);
    const byteNumbers = new Array(byteCharacters.length);
    for (let i = 0; i < byteCharacters.length; i++) {
      byteNumbers[i] = byteCharacters.charCodeAt(i);
    }
    const byteArray = new Uint8Array(byteNumbers);
    const blob = new Blob([byteArray], { type: format });

    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  } catch (err) {
    console.error("Audio export error:", err);
    alert("Could not export audio file.");
  }
}
